services:
  fintech-db:
    image: postgres:16-alpine
    container_name: fintech-db
    environment:
      POSTGRES_USER: fintech
      POSTGRES_PASSWORD: fintech
      POSTGRES_DB: fintech
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fintech-net
    restart: unless-stopped
  fintech-backend:
    build: .
    container_name: fintech-backend
    depends_on:
      - fintech-db
    env_file:
      - ../deploy/.env
    ports:
      - "8000:8000"
    networks:
      - fintech-net
    restart: unless-stopped
volumes:
  pgdata:
networks:
  fintech-net:
    name: fintech-net