"""User details

Revision ID: e0922855a2b9
Revises: 526bf0655e93
Create Date: 2026-05-16 11:51:41.369246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0922855a2b9'
down_revision: Union[str, Sequence[str], None] = '526bf0655e93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('middlename', sa.String(), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('second_lastname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))

    op.execute(
        "UPDATE users SET firstname = '', lastname = '', is_active = true, last_updated_at = NOW() WHERE firstname IS NULL")

    op.alter_column('users', 'firstname', nullable=False)
    op.alter_column('users', 'lastname', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'last_updated_at', nullable=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'last_updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'second_lastname')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'middlename')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
